ENVIRONMENT:
  MAX_EPISODE_STEPS: 500

SIMULATOR:
  FORWARD_STEP_SIZE: 0.25
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v1"

  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 1.25
    RADIUS: 0.18

  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: True

  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 70
    POSITION: [0, 1.25, 0]

  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 70
    MIN_DEPTH: 0.0
    MAX_DEPTH: 10.0
    POSITION: [0, 1.25, 0]

#  PANO_SINGLE_RGB_SENSOR:
#    WIDTH: 128
#    HEIGHT: 128
#    POSITION: [0, 1.25, 0]



TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]
  SUCCESS_DISTANCE: 0.1

  SENSORS: ['OBJECTGOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL', 'SOFT_SPL']

  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.1

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: train
  DATA_PATH: "../data/datasets/objectnav/mp3d/v1/{split}/{split}.json.gz"
  SCENES_DIR: "../data/scene_datasets/"
